### ISSUE TITLE
按照文档，加入这个jar包，但是找不到

### ISSUE THREAD

**Issue by liu-xinhui** [XenoAmess/p3c#129]
```
<dependency>
            <groupId>com.xenoamess.p3c</groupId>
            <artifactId>p3c-pmd</artifactId>
            <version>2.1.1.1x</version>
        </dependency>
```

Could not find artifact com.xenoamess.p3c:p3c-pmd:pom:2.1.1.1x in alimaven (http://maven.aliyun.com/nexus/content/groups/public/)

**Comment by XenoAmess** [comment]
我看了看central 确实没有 似乎上次发布跑失败了
抱歉
已重新发布至sonatype，应该几个小时后可见

**Comment by XenoAmess** [comment]
https://repo1.maven.org/maven2/com/xenoamess/p3c/p3c-pmd/2.1.1.1x/

验证：已经重新发布完毕
再次表示歉意
