### ISSUE TITLE
代码规约扫描能按照包维度或者正则进行忽略吗

### ISSUE THREAD

**Issue by Gahon1995** [XenoAmess/p3c#211]
**Is your feature request related to a problem? Please describe.**
项目中有部分代码为自动生成的代码，想忽略对该部分代码的检查，现在可以通过类名去屏蔽，对于生成类较多的就比较麻烦，所以希望能够按照包名正则进行屏蔽

**Describe the solution you'd like**
比如包 `com.test.gen.code`下的类都是自动生成的，可以通过`.*gen\.code.*来进行屏蔽`

**Comment by XenoAmess** [comment]
我确认下
你是希望屏蔽maven插件那边？
还是希望屏蔽idea插件那边？
还是两边都要屏蔽？

**Comment by XenoAmess** [comment]
另 最近公司事务繁忙，在每日12-16小时 每周7天工作中 可能会拖延几个星期

**Comment by Gahon1995** [comment]
> 我确认下
> 
> 你是希望屏蔽maven插件那边？
> 
> 还是希望屏蔽idea插件那边？
> 
> 还是两边都要屏蔽？

idea插件，辛苦辛苦

**Comment by XenoAmess** [comment]
我刚刚抽时间看了一下。似乎pmd没有对class寻找package名的功能，这是很奇怪的。

所以这个原理上就不太好做。

我已经正在去核实了，如果真的没有，那么我尽量给pmd加一个这种机制

只有当pmd那边加上这个功能了 能判别一个结点属于的类在哪个package下，你要的这个功能才能做

不过我不是很确定这个什么时间能完成 / pmd那边会不会允许我加这种机制

所以这个issue先保持开着 我持续跟进下吧

**Comment by XenoAmess** [comment]
https://github.com/pmd/pmd/issues/3897

**Comment by XenoAmess** [comment]
我试试看

**Comment by XenoAmess** [comment]
![image](https://user-images.githubusercontent.com/17455337/162583339-a88a86a9-76b1-45e0-a366-46ef68d57668.png)
他们是对的。有这个功能。那么你这个原理上可做。我试试看。

**Comment by XenoAmess** [comment]
搞定了。用法请查看https://github.com/XenoAmess/p3c/blob/xenoamess_maintain_fork/idea-plugin/README_cn.md

相应版本为https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-/versions/stable/167075

更新目前还在等待Jetbrains审核。等不及的话可以自行使用该链接下载。
