### ISSUE TITLE
idea version is 2022.1. java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by RichardZhengkay** [XenoAmess/p3c#234]
**Describe the bug**
1.java.lang.NoClassDefFoundError
2.Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.xenoamess.p3c.pmd.lang.java.util.namelist.NameListConfig

**Screenshots**
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/49510754/163168161-0b5c2f4f-b0c3-4950-8582-0e9c9d5eccef.png">
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/49510754/163168192-e8978f2c-fb1b-4459-8332-a81a3df5e6a3.png">

**Comment by XenoAmess** [comment]
@f1558

Please use https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-/versions/stable/168169

JetBrains is reviewing this update. Please expect it to be approved within two business days of the upload.

But  it IS usable.
