### ISSUE TITLE
插件可以打包成功，但是不可以安装

### ISSUE THREAD

**Issue by nickelzhang** [XenoAmess/p3c#259]
**Describe the bug**
插件可以打包成功，但是不可以安装，安装错误：Fail to load plugin descriptor from file Alibaba Java Coding Guidelines-2.1.1.4x.zip

**To Reproduce**
下载代码，maven构建pmd，按照说明gradle构建插件，IDEA安装插件

**Desktop (please complete the following information):**
 - OS: macos,ubuntu,windows一样的错误
 - Version idea,2019,2021,2022都有问题
但是调试是可以运行的

**Comment by XenoAmess** [comment]
欸 奇了怪了
试试这个分支呢？ xenoamess_maintain_fork_develop

**Comment by XenoAmess** [comment]
你打出来以后从哪个目录取的包？

**Comment by XenoAmess** [comment]
closed as long no response
