### ISSUE TITLE
Before Commit 扫描，只扫描本次commit改动的代码行

### ISSUE THREAD

**Issue by chenzz** [XenoAmess/p3c#294]
**Is your feature request related to a problem? Please describe.**
我改了3个类中的10行代码，结果before commit 扫描，扫描出了3个类中的几十个问题。。
我只能一个个对比，发现这几十个问题都不是我本次改动引入的问题，而是以前的历史问题

**Describe the solution you'd like**
Before Commit 扫描，只扫描本次commit改动的代码行，而不是对应的类的所有问题。

**Describe alternatives you've considered**
同上一条。

**Additional context**
我改了3个类中的10行代码，结果before commit 扫描，扫描出了3个类中的几十个问题。
如果修改对应类的所有问题，可能会引入bug      或者  时间不够

**Comment by XenoAmess** [comment]
不行。原因是同一个文件你的改动可能造成别人的代码出现新的pmd，哪怕不在同一行。

**Comment by XenoAmess** [comment]
所以不建议在pmd这层做这种事情。一般这种复杂需要的话，都是把每次的pmd结果录入系统，然后再模糊识别出已有问题，过滤掉。

**Comment by XenoAmess** [comment]
举个例子，如果你把一个switch的default删掉了，造成这个switch将会出现一个pmd，而这个pmd会挂在switch那行，而不是default那行（default那行已经被你删了事实上）
这就是改动了一行却对另外的行造成影响的案例

**Comment by XenoAmess** [comment]
closed as resolved
