### ISSUE TITLE
请问下idea plugin如何修改camelCase的白名单

### ISSUE THREAD

**Issue by chaoszcy** [XenoAmess/p3c#388]
想要把PO，MQ的关键字加入白名单，不在Lower或者Upper的提示中显示
按照readme的步骤，修改了p3c_config.x8l之后重新build idea-plugin后没有效果
说下我的步骤麻烦老师看下哪里有问题：
1.复制p3c_config.x8l到idea-plugin文件夹下，修改内容
2.gradlew clean buildPlugin
3.将idea-plugin/p3c-idea/build/idea-sandbox/plugins中生成的"Alibaba Java Coding Guidelines"文件夹压缩后导入idea

然而还是在提示我带PO的变量名不符合LowerCamelCase，我也尝试把p3c_config.x8l复制到idea-plugin/p3c-idea中，但还是没有效果

**Comment by XenoAmess** [comment]
那个文件是放在项目文件夹的
给你做了个例子
https://github.com/xenoamess-demo/demo_p3c_20230309

**Comment by chaoszcy** [comment]
好的，有效果了，感谢老师
