### ISSUE TITLE
IDEA ue 最新版本开始出现版本不匹配

### ISSUE THREAD

**Issue by gaiguodonfbu** [XenoAmess/p3c#393]
**Describe the bug**
IDEA ue 最新版本开始出现版本不匹配，不适用

**To Reproduce**
IDEA更新到最新

**Expected behavior**
正常使用

**Screenshots**
作者有没有时间提供一个方向，介绍一下怎么处理这样的问题

**Comment by Yurinann** [comment]
+1，请问是否能够支持 IDEA 2022.3.3 ？

**Comment by gaiguodonfbu** [comment]
更新到2023.1错误消失
